<?php

namespace Kombee\IndexAdvisor\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Kombee\IndexAdvisor\Services\DDLGenerator;

/**
 * Generates DROP INDEX migration files for PostgreSQL indexes
 * that have idx_scan = 0 (never used since last stats reset).
 *
 * These are already stored as 'DROP' type recommendations by IngestSlowLogCommand.
 *
 * Usage:
 *   php artisan index-advisor:drop-unused
 *   php artisan index-advisor:drop-unused --dry-run
 */
class DropUnusedCommand extends Command
{
    protected $signature = 'index-advisor:drop-unused {--dry-run : Print DDL without writing files}';

    protected $description = 'Generate DROP INDEX migrations for unused indexes';

    public function __construct(private DDLGenerator $ddl)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $driver = DB::getDriverName();
        if (! in_array($driver, ['pgsql', 'mysql'])) {
            $this->warn('This command is only supported for PostgreSQL and MySQL.');

            return Command::SUCCESS;
        }

        $dryRun = $this->option('dry-run');
        $excludedTables = (array) config('index_advisor.excluded_tables', []);


        $recs = DB::table('index_advisor_recommendations')
            ->where('index_type', 'DROP')
            ->where('status', 'pending')
            ->whereNotIn('table_name', $excludedTables)
            ->orderByDesc('score')
            ->get();

        if ($recs->isEmpty()) {
            $this->warn('No unused index candidates found. Run `php artisan index-advisor:ingest-slow-log` first.');

            return Command::SUCCESS;
        }

        $this->info("Found {$recs->count()} unused index(es)".($dryRun ? ' [DRY RUN]' : '').":\n");

        $created = 0;

        foreach ($recs as $rec) {
            $evidence = json_decode($rec->evidence ?? '{}', true);
            $indexName = $evidence['index_name'] ?? "idx_{$rec->table_name}_{$rec->column_name}";

            $upDDL = $this->ddl->generateDropIndex($driver, $rec->table_name, $indexName);
            $downDDL = $this->ddl->generateCreateIndex($driver, $rec->table_name, [$rec->column_name]);

            if ($dryRun) {
                $this->line("<comment>[{$rec->table_name}]</comment> Index: {$indexName}");
                $this->line("  UP:   {$upDDL}");
                $this->line("  DOWN: {$downDDL}");
                $this->newLine();

                continue;
            }

            $timestamp = now()->addSeconds($created)->format('Y_m_d_His');
            $migName = "drop_unused_index_{$rec->table_name}_{$rec->column_name}";
            $className = Str::studly($migName);
            $migFile = database_path("migrations/{$timestamp}_{$migName}.php");
            if (file_exists($migFile)) {
                $this->warn("Migration file already exists for {$migName}, skipping.");
                continue;
            }
            $path = $migFile;

            file_put_contents($path, $this->stub($className, $upDDL, $downDDL, $indexName, $rec->table_name, $driver));

            DB::table('index_advisor_recommendations')
                ->where('id', $rec->id)
                ->update(['status' => 'generated', 'updated_at' => now()]);

            $this->line("  <info>✅ Created:</info> database/migrations/{$timestamp}_{$migName}.php");
            $created++;
        }

        if (! $dryRun) {
            $this->newLine();
            $this->info("{$created} DROP migration(s) generated. Review carefully before running `php artisan migrate`.");
            $this->warn('⚠️  Always verify an index is truly unused before dropping in production.');
        }

        return Command::SUCCESS;
    }

    private function stub(string $className, string $up, string $down, string $indexName, string $table, string $driver): string
    {
        $upExported = var_export($up, true);
        $downExported = var_export($down, true);

        // Only disable transaction wrapping for PostgreSQL, where CONCURRENTLY
        // requires it. MySQL and other drivers benefit from transaction safety.
        $disableTx = ($driver === 'pgsql');
        $transactionProperty = $disableTx ? "public \$withinTransaction = false;\n    " : '';

        return <<<PHP
<?php

use Illuminate\\Database\\Migrations\\Migration;

/**
 * Auto-generated by Index Advisor — Drop Unused Index.
 *
 * Index : {$indexName}
 * Table : {$table}
 * Reason: Unused index (never used since last stats reset)
 *
 * ⚠️  Review before applying to production.
 */
return new class extends Migration {
    {$transactionProperty}public function up(): void
    {
        \\DB::unprepared({$upExported});
    }

    public function down(): void
    {
        \\DB::unprepared({$downExported});
    }
};
PHP;
    }
}
